contests/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
app_name = 'problem'
urlpatterns = [
     url(r'^$', views.home, name='home'),
     url(r'^add$', views.add, name='add'),
   
   

    ]

login/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

urlpatterns = [
    url(r'^admin2/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^contests/', include('contests.urls', namespace='contests')),


    url(r'^editproblem/', include('problem.urls', namespace='editproblem')),
    url(r'^submit/', include('submission.urls', namespace='code_editor')),

]

main/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from . import views, preblog, feeds, sitemaps


urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.Post.as_view(), name='post'),
    url(r'^page/(?P<pk>[0-9]+)/$', views.Page.as_view(), name='page'),
    url(r'^archive$', views.Archive.as_view(), name='archive'),
    url(r'^contact$', views.Contact.as_view(), name='contact'),
    url(r'^about$', views.About.as_view(), name='about'),
    url(r'^authors/(?P<pk>[0-9]+)/$', views.Author.as_view(), name='author'),

]

urlpatterns += [
    url(r'^admin/$', views.AdminIndex.as_view(), name='admin_index'),
    url(r'^admin/meta$', views.AdminBlogMeta.as_view(), name='admin_blog_meta'),
    url(r'^admin/posts$', views.AdminPosts.as_view(), name='admin_posts'),
    url(r'^admin/pages$', views.AdminPosts.as_view(), {'is_blog_page':True}, name='admin_pages'),
    url(r'^admin/post$', views.AdminPost.as_view(), name='admin_post'),
    url(r'^admin/page$', views.AdminPage.as_view(), name='admin_page'),
    url(r'^admin/posts/(?P<pk>[0-9]+)$', views.AdminPost.as_view(), name='admin_edit_post'),
    url(r'^admin/pages/(?P<pk>[0-9]+)$', views.AdminPage.as_view(), name='admin_edit_page'),
    url(r'^admin/posts/delete/(?P<pk>[0-9]+)$', views.DeletePost.as_view(), name='admin_delete_post'),
    url(r'^admin/pages/delete/(?P<pk>[0-9]+)$', views.DeletePage.as_view(), name='admin_delete_page'),
    url(r'^admin/tags/$', views.AdminTags.as_view(), name='admin_tags'),
    url(r'^admin/category/$', views.AdminCategory.as_view(), name='admin_category'),
    url(r'^admin/filter-posts$', views.AdminFilterPosts.as_view(), name='admin_filter_posts'),
    url(r'^admin/tags/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'tag'}, name='admin_delete_tag'),
    url(r'^admin/categories/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'category'}, name='admin_delete_category'),
    url(r'^admin/tags/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'tag'}, name='admin_edit_tag'),
    url(r'^admin/categories/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'category'}, name='admin_edit_category'),
]

urlpatterns += [
    url(r'^init$', preblog.BlogInitView.as_view()),
    url(r'^reinit-meta$', preblog.ReInitBlogMetaView.as_view()),
 ]

oj/oj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'oj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^',include('login.urls')),
]

src/oj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'oj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
]

contests/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Contests(models.Model):
    #id = models.IntegerField(primary_key=True,db_index=True)
    code = models.CharField(max_length=50)
    name = models.CharField(max_length=200)
    organiser = models.CharField(max_length=200)
    starttime = models.DateTimeField()
    endtime = models.DateTimeField()
    announcment = models.TextField()

    class Meta:
        managed = True
        db_table = 'contests'
        verbose_name_plural = 'contests'

src/contest/models.py
from django.db import models 
from problem.models import AbstractProblem


class ContestProblem(AbstractProblem):
    pass

contests/forms.py
from django import forms

class AddContest(forms.Form):
    code = forms.CharField(max_length=256)
    name = forms.CharField(max_length=256)
    organiser = forms.CharField(max_length=256)
    starttime=forms.DateTimeField()
    endtime=forms.DateTimeField()
    anouncement = forms.CharField(widget=forms.Textarea(attrs={'rows':20}))

main/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms

class NewPost(forms.Form):
    title = forms.CharField(max_length=256)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':20}))
    abstract = forms.CharField(widget=forms.Textarea(attrs={'rows':4}), required=False)
    author_id = forms.IntegerField(required=False, widget=forms.HiddenInput)
    # tag = forms.CharField(max_length=256, required=False)
    # category = forms.CharField(max_length=256, required=False)

class NewPage(forms.Form):
    title = forms.CharField(max_length=256)
    slug = forms.CharField(max_length=64)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':20}))
    author_id = forms.IntegerField(required=False, widget=forms.HiddenInput)

class CategoryForm(forms.Form):
    name = forms.CharField(max_length=256, label='Category Name')

class TagForm(forms.Form):
    tags = forms.CharField(max_length=256, label='Tags')

class BlogMetaForm(forms.Form):
    title = forms.CharField(max_length=256, label='Title')
    subtitle = forms.CharField(max_length=256, label='SubTitle')
    desc = forms.CharField(max_length=256, label='Description')
    author = forms.CharField(max_length=256, label='Owner')
    keywords = forms.CharField(max_length=256, label='Keywords')
    google_verify = forms.CharField(max_length=256, label='Google Site Verification', required=False)
    baidu_verify = forms.CharField(max_length=256, label='Baidu Site Verification', required=False)

contests/views.py
from django.shortcuts import render
from . import models, forms
# Create your views here.
def home(request):

 	return render(request, "contests/base.html")

# def add(request):
#     class AdminPost(View):
#     #template_name = ''

#@method_decorator(login_required)
def add(request, form=None):
    data = {}
    form_data = {}
    # if pk:
    #     try:
    #         pk = int(pk)
    #         post = models.Post.objects.get(pk=pk)
    #         checker = ObjectPermissionChecker(request.user)
    #         if not request.user.has_perm('main.change_post') \
    #             and not checker.has_perm('change_post', post):
    #             return HttpResponse('Forbidden')

    #         form_data['title'] = post.title
    #         form_data['content'] = post.raw
    #         form_data['abstract'] = post.abstract
    #         form_data['author_id'] = post.author.id
    #         data['edit_flag'] = True
    #     except models.Post.DoesNotExist:
    #         raise Http404
    # else:
    #     post = None
    # if not form:
    form = forms.AddContest(initial=form_data)
    data['form'] = form
    # data['posted_tags'] = [tag for tag in post.tags.all()] if post else None
    # data['posted_category'] = post.category if post else None
    # tags = models.Tag.objects.all()
    # data['tags'] = tags
    # catagories = models.Category.objects.all()
    # data['catagories'] = catagories
    # data['pk'] = pk
    return render(request,'contests/add.html', data)
			

src/contest/views.py
from django.shortcuts import render

# Create your views here.

templates/contests/add.html
{% extends "contests/base.html" %}
{% load static %}

{% block title %}

{% endblock %}




{% block main %}
{% load bootstrap3 %}
<form method="POST" action="" id='new-post'>
{% csrf_token %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                {% bootstrap_form form %}
            </div>
        
  

            </div>
            <br><br><br><br>
            <div class="row">
    
                <button type="submit" class="btn btn-primary" name="publish" value="publish">Publish</button>

        
        </div>
    </div>

            

    

</form>
{% endblock %}


{% block js %}
  <script src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script type="text/javascript">
    // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $('#btn-preview').on('click', function(event){
        // alert('preview clicked');
        var pk = {{ pk }};
        var post_url = '';
        if(pk == 0)
            post_url = "{% url 'main:admin_post' %}";
        else
            post_url = "{% url 'main:admin_edit_post' pk %}";

        // alert(post_url);

        $.ajax({
            url: post_url,
            type: 'POST',
            data: {
                    title: $('#id_title').val(),
                    content: $('#id_content').val(),
                    abstract: $('#id_abstract').val(),
                    preview: 'preview'

                },
            success: function(data){
                pk = $.trim(data);
                url = "{% url 'main:post' pk %}";
                window.open(url, '_blank');

            },
            async: false
          });
        event.preventDefault();
        return false
    });
</script>
{% endblock %}

templates/contests/base.html
<!DOCTYPE html>
<html lang="en" class="gr__todc_github_io">
<head>
    {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://todc.github.io/todc-bootstrap/favicon.ico">

    <title>Base</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/nvabar-fixed-top.css' %}" rel="stylesheet">

  <style id="style-1-cropbar-clipper">
.en-markup-crop-options {
    top: 18px !important;
    left: 50% !important;
    margin-left: -100px !important;
    width: 200px !important;
    border: 2px rgba(255,255,255,.38) solid !important;
    border-radius: 4px !important;
}

.en-markup-crop-options div div:first-of-type {
    margin-left: 0px !important;
}
</style></head>

  <body data-gr-c-s-loaded="true">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=submissions#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href=submissions#">Home</a></li>
            <li><a href=submissions#about">About</a></li>
            <li><a href=submissions#contact">Contact</a></li>
            <li class="dropdown">
              <a href=submissions#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href=submissions#">Action</a></li>
                <li><a href=submissions#">Another action</a></li>
                <li><a href=submissions#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href=submissions#">Separated link</a></li>
                <li><a href=submissions#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

    </div> 
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  

</body></html>